.PHONY: install test test-backend test-frontend dev-backend dev-frontend up down logs build migrate migrate-down migration seed db-up db-down db-logs clean up-prod down-prod logs-prod build-prod seed-prod

install:
	python3 -m venv .venv
	.venv/bin/pip install --upgrade pip
	.venv/bin/pip install -e ".[dev]"
	cd frontend && npm install

test: test-backend test-frontend

test-backend:
	.venv/bin/pytest

test-frontend:
	cd frontend && npm test

dev-backend:
	.venv/bin/uvicorn backend.app.main:app --reload --host 127.0.0.1 --port 8011

dev-frontend:
	cd frontend && npm run dev

up:
	docker compose up -d --build

down:
	docker compose down

logs:
	docker compose logs -f

build:
	docker compose build

migrate:
	.venv/bin/alembic upgrade head

migrate-down:
	.venv/bin/alembic downgrade base

# Create a new autogenerated migration. Usage: make migration name="add foo to bar"
migration:
	@if [ -z "$(name)" ]; then echo "usage: make migration name=\"short message\""; exit 1; fi
	.venv/bin/alembic revision --autogenerate -m "$(name)"

seed:
	.venv/bin/python -m backend.app.seed

db-up:
	docker compose up -d postgres

db-down:
	docker compose down

db-logs:
	docker compose logs -f postgres

# --- Production stack (docker-compose.prod.yml) ---
# Use these on the homelab / production server. Source bind-mounts are
# disabled, the backend runs alembic upgrade head on start (via the
# entrypoint), and the frontend is a Caddy container serving a built
# SPA + reverse-proxying /api/* to the backend.

up-prod:
	docker compose -f docker-compose.prod.yml up -d --build

down-prod:
	docker compose -f docker-compose.prod.yml down

logs-prod:
	docker compose -f docker-compose.prod.yml logs -f

build-prod:
	docker compose -f docker-compose.prod.yml build

seed-prod:
	docker compose -f docker-compose.prod.yml exec backend python -m backend.app.seed

clean:
	rm -rf .venv
	rm -rf frontend/node_modules
	rm -rf frontend/dist
	find . -type d -name __pycache__ -exec rm -rf {} +
	find . -type d -name .pytest_cache -exec rm -rf {} +
	find . -type d -name .ruff_cache -exec rm -rf {} +
